import { MenuCategory } from "./types";

const menu: MenuCategory[] = [
  {
    category: { ar: "فريش", en: "Fresh Juices" },
    items: [
      { name: { ar: "فريش مانجو", en: "Fresh Mango" }, price: 90, image: "/images/Fresh/fresh_mango.png" },
      { name: { ar: "فريش فراولة", en: "Fresh Strawberry" }, price: 85, image: "/images/Fresh/fresh_strawberry.png" },
      { name: { ar: "فريش كيوي", en: "Fresh Kiwi" }, price: 95, image: "/images/Fresh/fresh_kiwi.png" },
      { name: { ar: "فريش برتقال", en: "Fresh Orange" }, price: 80, image: "/images/Fresh/fresh_orange.png" },
      { name: { ar: "فريش بطيخ", en: "Fresh Watermelon" }, price: 80, image: "/images/Fresh/fresh_watermelon.png" },
      { name: { ar: "فريش كنتالوب", en: "Fresh Cantaloupe" }, price: 80, image: "/images/Fresh/fresh_cantaloupe.png" },
      { name: { ar: "فريش كوكتيل", en: "Fresh Cocktail" }, price: 100, image: "/images/Fresh/fresh_cocktail.png" },
      { name: { ar: "فريش موز بالبن", en: "Fresh Banana with Milk" }, price: 85, image: "/images/Fresh/fresh_banana.png" },
      { name: { ar: "فريش أفوكادو", en: "Fresh Avocado" }, price: 110, image: "/images/Fresh/fresh_avocado.png" },
      { name: { ar: "فريش ليمون نعناع", en: "Fresh Lemon Mint" }, price: 75, image: "/images/Fresh/fresh_lemon_mint.png" },
      { name: { ar: "فريش جوافة", en: "Fresh Guava" }, price: 80, image: "/images/Fresh/fresh_guava.png" },
      { name: { ar: "فريش ليمون", en: "Fresh Lemon" }, price: 60, image: "/images/Fresh/fresh_lemon.png" },
      { name: { ar: "فريش تين شوكي", en: "Fresh Prickly Pear" }, price: 60, image: "/images/Fresh/fresh_prickly_pear.png" },
      { name: { ar: "فروت دولار", en: "Fruit Dollar" }, price: 115, image: "/images/Fresh/fresh_dollar.png", description: "خلطة خاصة من الفواكه المنتقاة" },
      { name: { ar: "برتقال بالجزر", en: "Orange with Carrot" }, price: 90, image: "/images/Fresh/orange_carrot.png" },
      { name: { ar: "ليمون", en: "Lemon" }, price: 75, image: "/images/Fresh/lemon.png" },
      { name: { ar: "فروت سلاط", en: "Fruit Salad" }, price: 120, image: "/images/Fresh/fruit_salad.png" },
    ],
  },
  {
    category: { ar: "ميلك شيك", en: "Milkshakes" },
    items: [
      { name: { ar: "ميلك شيك أوريو", en: "Oreo Milkshake" }, price: 110, image: "/images/oreo_milkshake.png", description: "كريمي مع قطع الأوريو المقرمشة" },
      { name: { ar: "ميلك شيك كراميل", en: "Caramel Milkshake" }, price: 100, image: "/images/caramel_milkshake.png" },
      { name: { ar: "ميلك شيك فانيلا", en: "Vanilla Milkshake" }, price: 100, image: "/images/vanilla_milkshake.png" },
      { name: { ar: "ميلك شيك لوتس", en: "Lotus Milkshake" }, price: 110, image: "/images/lotus_milkshake.png", description: "كريمي مع كريمة اللوتس الشهيرة" },
      { name: { ar: "ميلك شيك شوكولاتة", en: "Chocolate Milkshake" }, price: 100, image: "/images/chocolate_milkshake.png", description: "بنكهة الشوكولاتة الغنية" },
      { name: { ar: "ميلك شيك فواكه", en: "Fruit Milkshake" }, price: 110, image: "/images/fruit_milkshake.png" },
      { name: { ar: "ميلك شيك فستق", en: "Pistachio Milkshake" }, price: 110, image: "/images/pistachio_milkshake.png" },
      { name: { ar: "ميلك شيك فراولة", en: "Strawberry Milkshake" }, price: 100, image: "/images/strawberry_milkshake.png" },
      { name: { ar: "ميلك شيك كيوي", en: "Kiwi Milkshake" }, price: 100, image: "/images/kiwi_milkshake.png" },
      { name: { ar: "ميلك شيك خوخ", en: "Peach Milkshake" }, price: 100, image: "/images/peach_milkshake.png" },
      { name: { ar: "ميلك شيك تين شوكي", en: "Prickly Pear Milkshake" }, price: 80, image: "/images/prickly_pear_milkshake.png" },
      { name: { ar: "ميلك شيك بلوبيري", en: "Blueberry Milkshake" }, price: 100, image: "/images/blueberry_milkshake.png" },
      { name: { ar: "ميلك شيك راسبيري", en: "Raspberry Milkshake" }, price: 100, image: "/images/raspberry_milkshake.png" },
      { name: { ar: "ميلك شيك مانجو", en: "Mango Milkshake" }, price: 100, image: "/images/mango_milkshake.png" },
      { name: { ar: "ميلك شيك نوتيلا", en: "Nutella Milkshake" }, price: 100, image: "/images/nutella_milkshake.png" },
      { name: { ar: "ميلك شيك كت كات", en: "Kit Kat Milkshake" }, price: 120, image: "/images/kitkat_milkshake.png" },
      { name: { ar: "ميلك شيك تشيزكيك", en: "Cheesecake Milkshake" }, price: 125, image: "/images/cheesecake_milkshake.png" },
      { name: { ar: "ميلك شيك موز بلوبيري", en: "Banana Blueberry Milkshake" }, price: 100, image: "/images/banana_blueberry_milkshake.png" },
    ],
  },
  {
    category: { ar: "زبادي", en: "Yoghurt" },
    items: [
      { name: { ar: "زبادي سادة", en: "Plain Yoghurt" }, price: 70, image: "/images/plain_yoghurt.jpg" },
      { name: { ar: "زبادي عسل", en: "Honey Yoghurt" }, price: 80, image: "/images/honey_yoghurt.jpg" },
      { name: { ar: "زبادي خوخ", en: "Peach Yoghurt" }, price: 85, image: "/images/peach_smoothie.jpg" },
      { name: { ar: "زبادي راسبيري", en: "Raspberry Yoghurt" }, price: 85, image: "/images/raspberry_smoothie.jpg" },
      { name: { ar: "زبادي باشون", en: "Passion Yoghurt" }, price: 85, image: "/images/passion_smoothie.jpg" },
      { name: { ar: "زبادي كيوي", en: "Kiwi Yoghurt" }, price: 85, image: "/images/kiwi_smoothie.jpg" },
      { name: { ar: "زبادي فراولة", en: "Strawberry Yoghurt" }, price: 85, image: "/images/strawberry_smoothie.jpg" },
      { name: { ar: "زبادي مانجو", en: "Mango Yoghurt" }, price: 85, image: "/images/mango_smoothie.jpg" },
      { name: { ar: "زبادي فانيليا", en: "Vanilla Yoghurt" }, price: 85, image: "/images/vanilla_yoghurt.jpg" },
      { name: { ar: "زبادي دبل بيري", en: "Double Berry Yoghurt" }, price: 85, image: "/images/double_berry_yoghurt.jpg" },
      { name: { ar: "زبادي بلوبيري", en: "Blueberry Yoghurt" }, price: 85, image: "/images/blueberry_smoothie.jpg" },
      { name: { ar: "زبادي بطيخ", en: "Watermelon Yoghurt" }, price: 85, image: "/images/watermelon_smoothie.jpg" },
      { name: { ar: "زبادي ليمون نعناع", en: "Lemon Mint Yoghurt" }, price: 70, image: "/images/lemon_mint.jpg" },
      { name: { ar: "زبادي ريد بيري", en: "Red Berry Yoghurt" }, price: 110, image: "/images/red_berry_smoothie.jpg" },
      { name: { ar: "زبادي ميكس", en: "Mix Yoghurt" }, price: 95, image: "/images/mix_smoothie.jpg" },
    ]
  },
  {
    category: { ar: "سموذي", en: "Smoothies" },
    items: [
      { name: { ar: "سموذي خوخ", en: "Peach Smoothie" }, price: 85, image: "/images/peach_smoothie.jpg" },
      { name: { ar: "سموذي راسبيري", en: "Raspberry Smoothie" }, price: 85, image: "/images/raspberry_smoothie.jpg" },
      { name: { ar: "سموذي باشون", en: "Passion Smoothie" }, price: 90, image: "/images/passion_smoothie.jpg" },
      { name: { ar: "سموذي ليمون نعناع", en: "Lemon Mint Smoothie" }, price: 85, image: "/images/lemon_mint_smoothie.jpg" },
      { name: { ar: "سموذي كيوي", en: "Kiwi Smoothie" }, price: 85, image: "/images/kiwi_smoothie.jpg" },
      { name: { ar: "سموذي مانجو", en: "Mango Smoothie" }, price: 85, image: "/images/mango_smoothie.jpg" },
      { name: { ar: "سموذي فراولة", en: "Strawberry Smoothie" }, price: 85, image: "/images/strawberry_smoothie.jpg" },
      { name: { ar: "سموذي بطيخ", en: "Watermelon Smoothie" }, price: 85, image: "/images/watermelon_smoothie.jpg" },
      { name: { ar: "سموذي ريد بيري", en: "Red Berry Smoothie" }, price: 85, image: "/images/red_berry_smoothie.jpg" },
      { name: { ar: "سموذي بلوبيري", en: "Blueberry Smoothie" }, price: 85, image: "/images/blueberry_smoothie.jpg" },
      { name: { ar: "سموذي ريد بول", en: "Red Bull Smoothie" }, price: 95, image: "/images/red_bull_smoothie.jpg" },
      { name: { ar: "سموذي ميكس", en: "Mix Smoothie" }, price: 100, image: "/images/mix_smoothie.jpg" },
      { name: { ar: "سموذي تلستار", en: "Telstar Smoothie" }, price: 100, image: "/images/telstar_smoothie.jpg" },
      { name: { ar: "سموذي دراجون", en: "Dragon Smoothie" }, price: 120, image: "/images/dragon_smoothie.jpg" },
      { name: { ar: "سموذي أناناس", en: "Pineapple Smoothie" }, price: 85, image: "/images/pineapple_smoothie.jpg" },
      { name: { ar: "سموذي ليمون", en: "Lemon Smoothie" }, price: 80, image: "/images/lemon_smoothie.jpg" },
      { name: { ar: "سموذي كنتالوب", en: "Cantaloupe Smoothie" }, price: 85, image: "/images/cantaloupe_smoothie.jpg" },
    ],
  },
  {
    category: { ar: "إضافات", en: "Extras" },
    items: [
      { name: { ar: "اكسترا فانيلا", en: "Vanilla Extra" }, price: 25, image: "/images/vanilla_extra.jpg" },
      { name: { ar: "اكسترا كراميل", en: "Caramel Extra" }, price: 25, image: "/images/caramel_extra.jpg" },
      { name: { ar: "اكسترا بندق", en: "Hazelnut Extra" }, price: 25, image: "/images/pine_nut_extra.jpg" },
      { name: { ar: "اكسترا شوكولاتة", en: "Chocolate Extra" }, price: 25, image: "/images/companies_extra.jpg" },
      { name: { ar: "اكسترا عسل", en: "Honey Extra" }, price: 20, image: "/images/special_extra.jpg" },
      { name: { ar: "اكسترا لبن", en: "Milk Extra" }, price: 20, image: "/images/light_extra.jpg" },
      { name: { ar: "اكسترا شاي", en: "Tea Extra" }, price: 15, image: "/images/tea_extra.jpg" },
      { name: { ar: "اكسترا فليفر", en: "Flavor Extra" }, price: 35, image: "/images/fliver_extra.jpg" },
      { name: { ar: "اكسترا وايت كريم", en: "White Cream Extra" }, price: 30, image: "/images/white_Crame_extra.jpg" },
      { name: { ar: "اكسترا بيستاشيو", en: "Pistachio Extra" }, price: 35, image: "/images/Pistachio_Extra.jpg" },
      { name: { ar: "توبينج", en: "Topping" }, price: 35, image: "/images/topping_extra.jpg" },
      { name: { ar: "شوت إسبريسو", en: "Espresso Shot" }, price: 30, image: "/images/espresso_shot.jpg" },
      { name: { ar: "اكسترا فواكه", en: "Fruit Extra" }, price: 30, image: "/images/fruit_mix.jpg" },
      { name: { ar: "اكسترا مكسرات", en: "Nuts Extra" }, price: 25, image: "/images/Nuts_Extra.jpg" },
    ],
  },
  {
    category: { ar: "سوفت درينك", en: "Soft Drinks" },
    items: [
      { name: { ar: "V كولا", en: "V Cola" }, price: 60, image: "/images/v_cola.jpg" },
      { name: { ar: "كولا", en: "Cola" }, price: 60, image: "/images/cola.jpg" },
      { name: { ar: "كولا زيرو", en: "Cola Zero" }, price: 60, image: "/images/cola_zero.jpg" },
      { name: { ar: "فيوري", en: "Fury" }, price: 60, image: "/images/fury.jpg" },
      { name: { ar: "ريد بول", en: "Red Bull" }, price: 100, image: "/images/red_bull.jpg" },
      { name: { ar: "بيبسي", en: "Pepsi" }, price: 60, image: "/images/pepsi.jpg" },
      { name: { ar: "بيبسي زيرو", en: "Pepsi Zero" }, price: 60, image: "/images/pepsi_zero.jpg" },
      { name: { ar: "سبرايت", en: "Sprite" }, price: 60, image: "/images/sprite.jpg" },
      { name: { ar: "فيروز", en: "Fayrouz" }, price: 60, image: "/images/fayrouz.jpg" },
      { name: { ar: "شويبس", en: "Schweppes" }, price: 60, image: "/images/schweppes.jpg" },
      { name: { ar: "بيريل", en: "Birell" }, price: 65, image: "/images/birell.jpg" },
      { name: { ar: "سيفن أب", en: "7 Up" }, price: 60, image: "/images/7up.jpg" },
      { name: { ar: "تويست", en: "Twist" }, price: 60, image: "/images/twist.jpg" },
      { name: { ar: "ميريندا", en: "Mirinda" }, price: 60, image: "/images/mirinda.jpg" },
      { name: { ar: "سبيرو سباتس", en: "Spiro Spathis" }, price: 35, image: "/images/spiro-spathis.jpg" },
      { name: { ar: "شيري كولا", en: "Cherry Cola" }, price: 85, image: "/images/cherry_cola.jpg" },
      { name: { ar: "مياه", en: "Water" }, price: 20, image: "/images/water.jpg" },
    ],
  },
  {
    category: { ar: "مشروبات ساخنة", en: "Hot Drinks" },
    items: [
      // الشاي والمشروبات العشبية
      { name: { ar: "شاي أحمر", en: "Red Tea" }, price: 35, image: "/images/red_tea.jpg" },
      { name: { ar: "يانسون", en: "Anise Tea" }, price: 40, image: "/images/yanson.jpg" },
      { name: { ar: "شاي نعناع", en: "Mint Tea" }, price: 40, image: "/images/mint_tea.jpg" },
      { name: { ar: "شاي أخضر", en: "Green Tea" }, price: 40, image: "/images/green_tea.jpg" },
      { name: { ar: "كوفي ميكس", en: "Coffee Mix" }, price: 40, image: "/images/coffee_mix.jpg" },
      { name: { ar: "شاي بنكهة", en: "Flavored Tea" }, price: 50, image: "/images/flavored_tea.jpg" },
      { name: { ar: "حمص الشام", en: "Hummus El Sham" }, price: 50, image: "/images/hummus_el_sham.jpg" },
      { name: { ar: "كورتادو", en: "Cortado" }, price: 50, image: "/images/cortado.jpg" },
      { name: { ar: "شاي بحليب", en: "Milk Tea" }, price: 60, image: "/images/milk_tea.jpg" },
      { name: { ar: "ميكس أعشاب", en: "Herbal Mix" }, price: 55, image: "/images/herbal_mix.jpg" },

      // مشروبات ساخنة متنوعة
      { name: { ar: "سيدر ساخن", en: "Hot Cider" }, price: 60, image: "/images/hot_cider.jpg" },
      { name: { ar: "ليمون ساخن", en: "Hot Lemon" }, price: 45, image: "/images/hot_lemon.jpg" },
      { name: { ar: "جنزبيل", en: "Ginger Tea" }, price: 50, image: "/images/ginger_tea.jpg" },
      { name: { ar: "نسكافيه", en: "Nescafe" }, price: 75, image: "/images/nescafe.jpg" },
      { name: { ar: "سحلب", en: "Sahlab" }, price: 70, image: "/images/sahlab.jpg" },

      // قهوة تركي وإسبريسو
      { name: { ar: "قهوة تركي (سنجل)", en: "Turkish Coffee (Single)" }, price: 45, image: "/images/turkish_coffee_single.jpg" },
      { name: { ar: "قهوة تركي (دبل)", en: "Turkish Coffee (Double)" }, price: 55, image: "/images/turkish_coffee_double.jpg" },
      { name: { ar: "إسبريسو (سنجل)", en: "Espresso (Single)" }, price: 50, image: "/images/espresso_single.jpg" },
      { name: { ar: "إسبريسو (دبل)", en: "Espresso (Double)" }, price: 70, image: "/images/espresso_double.jpg" },
      { name: { ar: "ميكاتو (سنجل)", en: "Macchiato (Single)" }, price: 60, image: "/images/macchiato_single.jpg" },
      { name: { ar: "ميكاتو (دبل)", en: "Macchiato (Double)" }, price: 70, image: "/images/macchiato_double.jpg" },

      // أنواع القهوة المميزة
      { name: { ar: "قهوة فرنسية", en: "French Coffee" }, price: 65, image: "/images/french_coffee.jpg" },
      { name: { ar: "قهوة بندق", en: "Hazelnut Coffee" }, price: 65, image: "/images/hazelnut_coffee.jpg" },
      { name: { ar: "لاتيه بندق", en: "Hazelnut Latte" }, price: 60, image: "/images/hazelnut_latte.jpg" },
      { name: { ar: "هوت شوكليت", en: "Hot Chocolate" }, price: 75, image: "/images/hot_chocolate.jpg" },
      { name: { ar: "كراميل ميكاتو", en: "Caramel Macchiato" }, price: 70, image: "/images/caramel_macchiato.jpg" },
      { name: { ar: "اسبنش لاتيه", en: "Spanish Latte" }, price: 60, image: "/images/spanish_latte.jpg" },
      { name: { ar: "كابتشينو L", en: "Cappuccino Large" }, price: 85, image: "/images/cappuccino_large.jpg" },
      { name: { ar: "كابتشينو M", en: "Cappuccino Medium" }, price: 75, image: "/images/cappuccino_medium.jpg" },
      { name: { ar: "فلات وايت", en: "Flat White" }, price: 75, image: "/images/flat_white.jpg" },
      { name: { ar: "أمريكان كوفي", en: "American Coffee" }, price: 80, image: "/images/american_coffee.jpg" },
      { name: { ar: "موكا", en: "Mocha" }, price: 70, image: "/images/mocha.jpg" },
      { name: { ar: "لاتيه لوتس", en: "Lotus Latte" }, price: 90, image: "/images/lotus_latte.jpg" },
      { name: { ar: "لاتيه كوكيز", en: "Cookie Latte" }, price: 90, image: "/images/cookie_latte.jpg" },
    ],
  },
  {
    category: { ar: "موخيتو", en: "Mojitos" },
    items: [
      { name: { ar: "موخيتو كلاسيك", en: "Classic Mojito" }, price: 80, image: "/images/classic_mojito.jpg" },
      { name: { ar: "موخيتو ريد بول", en: "Red Bull Mojito" }, price: 110, image: "/images/red_bull_mojito.jpg" },
      { name: { ar: "موخيتو راسبيري", en: "Raspberry Mojito" }, price: 80, image: "/images/raspberry_mojito.jpg" },
      { name: { ar: "موخيتو بلوبيري", en: "Blueberry Mojito" }, price: 80, image: "/images/blueberry_mojito.jpg" },
      { name: { ar: "موخيتو خوخ", en: "Peach Mojito" }, price: 80, image: "/images/peach_mojito.jpg" },
      { name: { ar: "موخيتو باشون", en: "Passion Mojito" }, price: 85, image: "/images/passion_mojito.jpg" },
      { name: { ar: "موخيتو فراولة", en: "Strawberry Mojito" }, price: 80, image: "/images/strawberry_mojito.jpg" },
      { name: { ar: "موخيتو كيوي", en: "Kiwi Mojito" }, price: 80, image: "/images/kiwi_mojito.jpg" },
      { name: { ar: "موخيتو شيري", en: "Cherry Mojito" }, price: 80, image: "/images/cherry_mojito.jpg" },
      { name: { ar: "موخيتو بطيخ", en: "Watermelon Mojito" }, price: 80, image: "/images/watermelon_mojito.jpg" },
      { name: { ar: "موخيتو أناناس", en: "Pineapple Mojito" }, price: 80, image: "/images/pineapple_mojito.jpg" },
      { name: { ar: "موخيتو مانجو", en: "Mango Mojito" }, price: 80, image: "/images/mango_mojito.jpg" },
      { name: { ar: "موخيتو رمان", en: "Pomegranate Mojito" }, price: 80, image: "/images/pomegranate_mojito.jpg" },
      { name: { ar: "موخيتو دولار", en: "Dollar Mojito" }, price: 130, image: "/images/dollar_mojito.jpg" },
      { name: { ar: "موخيتو فيغاس", en: "Vegas Mojito" }, price: 95, image: "/images/vegas_mojito.jpg" },
      { name: { ar: "موخيتو شيري كولا", en: "Cherry Cola Mojito" }, price: 80, image: "/images/cherry_cola_mojito.jpg" },
      { name: { ar: "همر هيد", en: "Hammer Head" }, price: 100, image: "/images/hammer_head.jpg" },
      { name: { ar: "تكنو", en: "Techno" }, price: 95, image: "/images/techno.jpg" },
    ]
  },
  {
    category: { ar: "صن شاين", en: "Sunshine Drinks" },
    items: [
      { name: { ar: "صن شاين كلاسيك", en: "Classic Sunshine" }, price: 85, image: "/images/classic_sunshine.jpg" },
      { name: { ar: "صن شاين خوخ", en: "Peach Sunshine" }, price: 85, image: "/images/peach_sunshine.jpg" },
      { name: { ar: "صن شاين رمان", en: "Pomegranate Sunshine" }, price: 85, image: "/images/pomegranate_sunshine.jpg" },
      { name: { ar: "صن شاين بلوبيري", en: "Blueberry Sunshine" }, price: 85, image: "/images/blueberry_sunshine.jpg" },
      { name: { ar: "صن شاين نعناع", en: "Mint Sunshine" }, price: 85, image: "/images/mint_sunshine.jpg" },
      { name: { ar: "صن شاين ليمون", en: "Lemon Sunshine" }, price: 85, image: "/images/lemon_sunshine.jpg" },
      { name: { ar: "صن شاين كيوي", en: "Kiwi Sunshine" }, price: 80, image: "/images/kiwi_sunshine.jpg" },
      { name: { ar: "صن شاين فراولة", en: "Strawberry Sunshine" }, price: 85, image: "/images/strawberry_sunshine.jpg" },
      { name: { ar: "صن شاين مانجو", en: "Mango Sunshine" }, price: 85, image: "/images/mango_sunshine.jpg" },
      { name: { ar: "صن شاين ميكس", en: "Mix Sunshine" }, price: 85, image: "/images/mix_sunshine.jpg" },
      { name: { ar: "صن شاين أناناس", en: "Pineapple Sunshine" }, price: 90, image: "/images/pineapple_sunshine.jpg" },
      { name: { ar: "صن شاين بطيخ", en: "Watermelon Sunshine" }, price: 85, image: "/images/watermelon_sunshine.jpg" },
      { name: { ar: "صن شاين راسبيري", en: "Raspberry Sunshine" }, price: 85, image: "/images/raspberry_sunshine.jpg" },
      { name: { ar: "صن شاين باشون فروت", en: "Passion Fruit Sunshine" }, price: 85, image: "/images/passion_sunshine.jpg" },
      { name: { ar: "صن شاين فانيليا", en: "Vanilla Sunshine" }, price: 85, image: "/images/vanilla_sunshine.jpg" },
      { name: { ar: "صن شاين شيري كولا", en: "Cherry Cola Sunshine" }, price: 85, image: "/images/cherry_cola_sunshine.jpg" },
    ],
  },
  {
    category: { ar: "كوكتيل", en: "Cocktails" },
    items: [
      { name: { ar: "دولار", en: "Dollar" }, price: 130, image: "/images/dollar_cocktail.jpg" },
      { name: { ar: "باور دولار", en: "Power Dollar" }, price: 120, image: "/images/power_dollar.jpg" },
      { name: { ar: "دانون دولار", en: "Danone Dollar" }, price: 100, image: "/images/danone_dollar.jpg" },
      { name: { ar: "ماجيك", en: "Magic" }, price: 100, image: "/images/magic_cocktail.jpg" },
      { name: { ar: "بيناكولادا", en: "Pina Colada" }, price: 100, image: "/images/pina_colada.jpg" },
      { name: { ar: "راسبيري كولادا", en: "Raspberry Colada" }, price: 85, image: "/images/raspberry_colada.jpg" },
      { name: { ar: "بيانكونيرا", en: "Bianconera" }, price: 90, image: "/images/bianconera.jpg" },
      { name: { ar: "أفوكادو عسل", en: "Avocado Honey" }, price: 120, image: "/images/avocado_honey.jpg" },
      { name: { ar: "أفوكادو دولار", en: "Avocado Dollar" }, price: 130, image: "/images/avocado_dollar.jpg" },
      { name: { ar: "استوائي أفوكادو", en: "Tropical Avocado" }, price: 90, image: "/images/tropical_avocado.jpg" },
      { name: { ar: "همر كوكتيل", en: "Hammer Cocktail" }, price: 90, image: "/images/hammer_cocktail.jpg" },
    ],
  },
  {
    category: { ar: "فرابيه", en: "Frappes" },
    items: [
      { name: { ar: "فرابتشينو", en: "Frappuccino" }, price: 90, image: "/images/frappuccino.jpg" },
      { name: { ar: "كراميل فرابيه", en: "Caramel Frappe" }, price: 85, image: "/images/caramel_frappe.jpg" },
      { name: { ar: "أوريو فرابيه", en: "Oreo Frappe" }, price: 90, image: "/images/oreo_frappe.jpg" },
      { name: { ar: "فرابيه موكا", en: "Mocha Frappe" }, price: 85, image: "/images/mocha_frappe.jpg" },
      { name: { ar: "فرابيه لوتس", en: "Lotus Frappe" }, price: 90, image: "/images/lotus_frappe.jpg" },
      { name: { ar: "فرابيه شوكولاتة", en: "Chocolate Frappe" }, price: 85, image: "/images/chocolate_frappe.jpg" },
      { name: { ar: "فرابيه نوتيلا", en: "Nutella Frappe" }, price: 90, image: "/images/nutella_frappe.jpg" }
    ],
  },
  {
    category: { ar: "ايس كوفي", en: "Iced Coffee" },
    items: [
      { name: { ar: "ايس لاتيه", en: "Iced Latte" }, price: 65, image: "/images/iced_latte.jpg" },
      { name: { ar: "ايس موكا", en: "Iced Mocha" }, price: 75, image: "/images/iced_mocha.jpg" },
      { name: { ar: "ايس كوفي", en: "Iced Coffee" }, price: 70, image: "/images/iced_coffee.jpg" },
    ],
  },
  {
    category: { ar: "وافل", en: "Waffles" },
    items: [
      { name: { ar: "وافل شوكولاتة", en: "Chocolate Waffle" }, price: 120, image: "/images/chocolate_waffle.jpg" },
      { name: { ar: "وافل نوتيلا", en: "Nutella Waffle" }, price: 140, image: "/images/nutella_waffle.jpg" },
      { name: { ar: "وافل فستق", en: "Pistachio Waffle" }, price: 150, image: "/images/pistachio_waffle.jpg" },
      { name: { ar: "وافل لوتس", en: "Lotus Waffle" }, price: 130, image: "/images/lotus_waffle.jpg" },
      { name: { ar: "وافل ميكس", en: "Mix Waffle" }, price: 170, image: "/images/mix_waffle.jpg" },
      { name: { ar: "وافل سوبر ميكس", en: "Super Mix Waffle" }, price: 200, image: "/images/super_mix_waffle.jpg" },
      { name: { ar: "وافل دابل سوبر ميكس", en: "Double Super Mix Waffle" }, price: 250, image: "/images/double_super_mix_waffle.jpg" },
      { name: { ar: "دولار وافل", en: "Dollar Waffle" }, price: 250, image: "/images/dollar_waffle.jpg" },
      { name: { ar: "وافل كراميل", en: "Caramel Waffle" }, price: 100, image: "/images/caramel_waffle.jpg" },
      { name: { ar: "وافل تشيز كيك", en: "Cheesecake Waffle" }, price: 125, image: "/images/cheesecake_waffle.jpg" },
      { name: { ar: "وافل فواكه", en: "Fruit Waffle" }, price: 160, image: "/images/fruit_waffle.jpg" },
      { name: { ar: "وافل نوتيلا موز", en: "Nutella Banana Waffle" }, price: 160, image: "/images/nutella_banana_waffle.jpg" },
      { name: { ar: "وافل كيندر", en: "Kinder Waffle" }, price: 150, image: "/images/kinder_waffle.jpg" },
    ],
  },
  {
    category: { ar: "كيك", en: "Cakes" },
    items: [
      { name: { ar: "شوكليت كيك", en: "Chocolate Cake" }, price: 90, image: "/images/chocolate_cake.jpg" },
      { name: { ar: "تشيزكيك", en: "Cheesecake" }, price: 90, image: "/images/cheesecake.jpg" },
      { name: { ar: "مولتن كيك", en: "Molten Cake" }, price: 130, image: "/images/molten_cake.jpg" },
      { name: { ar: "مولتن كيك نوتيلا", en: "Nutella Molten Cake" }, price: 150, image: "/images/nutella_molten_cake.jpg" },
      { name: { ar: "مولتن نوتيلا ايس كريم", en: "Nutella Molten Ice Cream" }, price: 160, image: "/images/nutella_molten_ice_cream.jpg" },
    ],
  },
  {
    category: { ar: "براونيز", en: "Brownies" },
    items: [
      { name: { ar: "براونيز", en: "Brownies" }, price: 90, image: "/images/brownies.jpg" },
      { name: { ar: "براونيز ايس كريم", en: "Brownies Ice Cream" }, price: 110, image: "/images/brownies_ice_cream.jpg" },
    ],
  },
  {
    category: { ar: "حلويات خاصة", en: "Special Desserts" },
    items: [
      { name: { ar: "أوريو مادنس", en: "Oreo Madness" }, price: 120, image: "/images/oreo_madness.jpg" },
      { name: { ar: "تشيز مادني", en: "Cheese Madness" }, price: 130, image: "/images/cheese_madness.jpg" },
      { name: { ar: "طاجن نوتيلا", en: "Nutella Tagine" }, price: 150, image: "/images/nutella_tagine.jpg" },
      { name: { ar: "فولكانو نوتيلا", en: "Nutella Volcano" }, price: 110, image: "/images/nutella_volcano.jpg" },
      { name: { ar: "بنانا سبليت", en: "Banana Split" }, price: 100, image: "/images/banana_split.jpg" },
    ],
  },
  {
    category: { ar: "أم علي", en: "Om Ali" },
    items: [
      { name: { ar: "أم علي كبيرة", en: "Large Om Ali" }, price: 125, image: "/images/om_ali_large.jpg" },
      { name: { ar: "أم علي صغيرة", en: "Small Om Ali" }, price: 90, image: "/images/om_ali_small.jpg" },
      { name: { ar: "بليلة", en: "Belila" }, price: 75, image: "/images/belila.jpg" },
    ],
  },
  {
    category: { ar: "فواكه وايس كريم", en: "Fruits & Ice Cream" },
    items: [
      { name: { ar: "طبق فاكهة كبير", en: "Large Fruit Plate" }, price: 300, image: "/images/fruit_plate_large.jpg" },
      { name: { ar: "طبق فاكهة صغير", en: "Small Fruit Plate" }, price: 200, image: "/images/fruit_plate_small.jpg" },
      { name: { ar: "بولة ايس كريم", en: "Ice Cream Scoop" }, price: 45, image: "/images/ice_cream.jpg" },
    ],
  },
  {
    category: { ar: "شيشة", en: "Shisha" },
    items: [
      { name: { ar: "شيشة فواكه", en: "Fruit Shisha" }, price: 140, image: "/images/shisha_fruit.jpg", description: "فتحة الجهاز بـ140ج" },
      { name: { ar: "شيشة ميكس فواكه", en: "Mixed Fruit Shisha" }, price: 165, image: "/images/shisha_mix.jpg" },
      { name: { ar: "معسل", en: "Molasses" }, price: 40, image: "/images/shisha_molasses.jpg" },
      { name: { ar: "لي", en: "Shisha Hose" }, price: 25, image: "/images/shisha_hose.jpg" },
      { name: { ar: "غيار ميكس", en: "Mix Refill" }, price: 100, image: "/images/shisha_refill.jpg" },
      { name: { ar: "غيار معسل", en: "Molasses Refill" }, price: 35, image: "/images/shisha_molasses_refill.jpg" },
    ],
  },
  {
    category: { ar: "بلايستيشن", en: "PlayStation" },
    items: [
      { name: { ar: "بلايستيشن 4 سينجل", en: "PlayStation 4 Single" }, price: 150, image: "/images/playstation.jpg", description: "فتحة الجهاز بـ150ج" },
      { name: { ar: "بلايستيشن 4 مالتي", en: "PlayStation 4 Multi" }, price: 150, image: "/images/playstation.jpg", description: "فتحة الجهاز بـ150ج" },
      { name: { ar: "بلايستيشن 5 سينجل", en: "PlayStation 5 Single" }, price: 200, image: "/images/playstation.jpg", description: "فتحة الجهاز بـ200ج" },
      { name: { ar: "بلايستيشن 5 مالتي", en: "PlayStation 5 Multi" }, price: 200, image: "/images/playstation.jpg", description: "فتحة الجهاز بـ200ج" },
    ],
  },
];

export default menu;