import { MenuCategory } from "./types";


const menu:MenuCategory[] = [
  {
    category: { ar: "ميلك شيك", en: "Milkshake" },
    items: [
      { name: { ar: "ميلك شيك أوريو", en: "Oreo Milkshake" }, price: 95, image: "/images/oreo_milkshake.png", description: "Milkshake with Oreo cookies" },
      { name: { ar: "ميلك شيك كراميل", en: "Caramel Milkshake" }, price: 70, image: "/images/caramel_milkshake.jpg" },
      { name: { ar: "ميلك شيك فانيلا", en: "Vanilla Milkshake" }, price: 70, image: "/images/vanilla_milkshake.png" },
      { name: { ar: "ميلك شيك لوتس", en: "Lotus Milkshake" }, price: 75, image: "/images/lotus_milkshake.webp", description: "Creamy milkshake with Lotus biscuit spread" },
      { name: { ar: "ميلك شيك شوكلت", en: "Chocolate Milkshake" }, price: 70, image: "/images/chocolate_milkshake.jpg",description: "Milkshake with rich chocolate flavor" },
      { name: { ar: "ميلك شيك فواكه", en: "Fruit Milkshake" }, price: 80, image: "/images/fruit_milkshake.jpg" },
      { name: { ar: "ميلك شيك فستق", en: "Pistachio Milkshake" }, price: 70, image: "/images/pistachio_milkshake.jpg" },
      { name: { ar: "ميلك شيك فراولة", en: "Strawberry Milkshake" }, price: 70, image: "/images/strawberry_milkshake.jpg" },
      { name: { ar: "ميلك شيك كيوي", en: "Kiwi Milkshake" }, price: 95, image: "/images/kiwi_milkshake.jpg" },
      { name: { ar: "ميلك شيك خوخ", en: "Peach Milkshake" }, price: 70, image: "/images/peach_milkshake.jpg" },
      { name: { ar: "ميلك شيك بلوبيري", en: "Blueberry Milkshake" }, price: 70, image: "/images/blueberry_milkshake.jpg" },
      { name: { ar: "ميلك شيك راسبيري", en: "Raspberry Milkshake" }, price: 60, image: "/images/raspberry_milkshake.jpg" },
      { name: { ar: "ميلك شيك مانجو", en: "Mango Milkshake" }, price: 115, image: "/images/mango_milkshake.jpg" },
    ],
  },
  {
    category: { ar: "عصائر فريش", en: "Fresh Juices" },
    items: [
      { name: { ar: "فريش مانجو", en: "Fresh Mango" }, price: 95, image: "/images/fresh_mango.jpg" },
      { name: { ar: "فريش فراولة", en: "Fresh Strawberry" }, price: 70, image: "/images/fresh_strawberry.jpg" },
      { name: { ar: "فريش كيوي", en: "Fresh Kiwi" }, price: 95, image: "/images/fresh_kiwi.jpg" },
      { name: { ar: "فريش برتقال", en: "Fresh Orange" }, price: 70, image: "/images/fresh_orange.jpg" },
      { name: { ar: "فريش بطيخ", en: "Fresh Watermelon" }, price: 75, image: "/images/fresh_watermelon.jpg" },
      { name: { ar: "فريش كنتالوب", en: "Fresh Cantaloupe" }, price: 70, image: "/images/fresh_cantaloupe.jpg" },
      { name: { ar: "فريش كوكتيل", en: "Fresh Cocktail" }, price: 80, image: "/images/fresh_cocktail.jpg" },
      { name: { ar: "فريش موز", en: "Fresh Banana" }, price: 70, image: "/images/fresh_banana.jpg" },
      { name: { ar: "فريش أفريكانو", en: "Fresh Africano" }, price: 110, image: "/images/fresh_africano.jpg" },
      { name: { ar: "فريش ليمون نعناع", en: "Fresh Lemon Mint" }, price: 60, image: "/images/fresh_lemon_mint.jpg" },
      { name: { ar: "فريش جوافة", en: "Fresh Guava" }, price: 70, image: "/images/fresh_guava.jpg" },
      { name: { ar: "فريش ليمون", en: "Fresh Lemon" }, price: 60, image: "/images/fresh_lemon.jpg" },
      { name: { ar: "سلطة فواكه", en: "Fruit Salad" }, price: 115, image: "/images/fruit_salad.jpg" },
    ],
  },
  {
    category: { ar: "اسموزي", en: "Smoothies" },
    items: [
      { name: { ar: "اسموزي خوخ", en: "Peach Smoothie" }, price: 85, image: "/images/peach_smoothie.jpg" },
      { name: { ar: "اسموزي راسبيري", en: "Raspberry Smoothie" }, price: 85, image: "/images/raspberry_smoothie.jpg" },
      { name: { ar: "اسموزي بابل جم", en: "Bubblegum Smoothie" }, price: 85, image: "/images/bubblegum_smoothie.jpg" },
      { name: { ar: "اسموزي ليمون نعناع", en: "Lemon Mint Smoothie" }, price: 85, image: "/images/lemon_mint_smoothie.jpg" },
      { name: { ar: "اسموزي كيوي", en: "Kiwi Smoothie" }, price: 85, image: "/images/kiwi_smoothie.jpg" },
      { name: { ar: "اسموزي مانجو", en: "Mango Smoothie" }, price: 85, image: "/images/mango_smoothie.jpg" },
      { name: { ar: "اسموزي فراولة", en: "Strawberry Smoothie" }, price: 85, image: "/images/strawberry_smoothie.jpg" },
      { name: { ar: "اسموزي بطيخ", en: "Watermelon Smoothie" }, price: 85, image: "/images/watermelon_smoothie.jpg" },
      { name: { ar: "اسموزي رد بيري", en: "Red Berry Smoothie" }, price: 85, image: "/images/red_berry_smoothie.jpg" },
      { name: { ar: "اسموزي بلوبيري", en: "Blueberry Smoothie" }, price: 85, image: "/images/blueberry_smoothie.jpg" },
      { name: { ar: "اسموزي ميكس", en: "Mix Smoothie" }, price: 95, image: "/images/mix_smoothie.jpg" },
    ],
  },
  {
    category: { ar: "حلويات", en: "Desserts" },
    items: [
      { name: { ar: "وافل شوكولاتة", en: "Chocolate Waffle" }, price: null, image: "/images/chocolate_waffle.jpg" },
      { name: { ar: "وافل نوتيلا", en: "Nutella Waffle" }, price: null, image: "/images/nutella_waffle.jpg" },
      { name: { ar: "وافل فستق", en: "Pistachio Waffle" }, price: null, image: "/images/pistachio_waffle.jpg" },
      { name: { ar: "وافل لوتس", en: "Lotus Waffle" }, price: null, image: "/images/lotus_waffle.jpg" },
      { name: { ar: "وافل ميكس", en: "Mix Waffle" }, price: null, image: "/images/mix_waffle.jpg" },
      { name: { ar: "وافل كراميل", en: "Caramel Waffle" }, price: null, image: "/images/caramel_waffle.jpg" },
      { name: { ar: "وافل تشيز كيك", en: "Cheesecake Waffle" }, price: null, image: "/images/cheesecake_waffle.jpg" },
      { name: { ar: "أم علي كبيرة", en: "Large Om Ali" }, price: null, image: "/images/om_ali_large.jpg" },
      { name: { ar: "أم علي صغيرة", en: "Small Om Ali" }, price: null, image: "/images/om_ali_small.jpg" },
      { name: { ar: "أرز باللبن", en: "Rice Pudding" }, price: null, image: "/images/rice_pudding.jpg" },
    ],
  },
  {
  category: { ar: "مشروبات ساخنة", en: "Hot Drinks" },
  items: [
    { name: { ar: "شاي أحمر", en: "Red Tea" }, price: 35, image: "/images/red_tea.jpg" },
    { name: { ar: "شاي أخضر", en: "Green Tea" }, price: 40, image: "/images/green_tea.jpg" },
    { name: { ar: "شاي بنكهة", en: "Flavored Tea" }, price: 50, image: "/images/flavored_tea.jpg" },
    { name: { ar: "سيدر ساخن", en: "Hot Cider" }, price: 60, image: "/images/hot_cider.jpg" },
    { name: { ar: "قهوة تركي (سنجل)", en: "Turkish Coffee (Single)" }, price: 45, image: "/images/turkish_coffee_single.jpg" },
    { name: { ar: "قهوة تركي (دابل)", en: "Turkish Coffee (Double)" }, price: 55, image: "/images/turkish_coffee_double.jpg" },
    { name: { ar: "قهوة فرنسية", en: "French Coffee" }, price: 65, image: "/images/french_coffee.jpg" },
    { name: { ar: "إسبريسو (سنجل)", en: "Espresso (Single)" }, price: 50, image: "/images/espresso_single.jpg" },
    { name: { ar: "إسبريسو (دابل)", en: "Espresso (Double)" }, price: 60, image: "/images/espresso_double.jpg" },
    { name: { ar: "هوت شوكليت", en: "Hot Chocolate" }, price: 70, image: "/images/hot_chocolate.jpg" },
    { name: { ar: "كراميل ميكاتو", en: "Caramel Macchiato" }, price: 70, image: "/images/caramel_macchiato.jpg" },
    { name: { ar: "كابتشينو", en: "Cappuccino" }, price: 85, image: "/images/cappuccino.jpg" },
    { name: { ar: "فلات وايت", en: "Flat White" }, price: 65, image: "/images/flat_white.jpg" },
    { name: { ar: "موكا", en: "Mocha" }, price: 70, image: "/images/mocha.jpg" },
    { name: { ar: "شاي زنجبيل", en: "Ginger Tea" }, price: 45, image: "/images/ginger_tea.jpg" },
    { name: { ar: "شاي يانسون", en: "Anise Tea" }, price: 35, image: "/images/anise_tea.jpg" },
    { name: { ar: "شاي نعناع", en: "Mint Tea" }, price: 35, image: "/images/mint_tea.jpg" },
    { name: { ar: "نسكافيه", en: "Nescafe" }, price: 35, image: "/images/nescafe.jpg" },
    { name: { ar: "ليمون ساخن", en: "Hot Lemon" }, price: 45, image: "/images/hot_lemon.jpg" },
    { name: { ar: "مشروب أعشاب", en: "Herbal Mix" }, price: 55, image: "/images/herbal_mix.jpg" },
  ],
},
{
  category: { ar: "إضافات", en: "Extras" },
  items: [
    { name: { ar: "فانيلا", en: "Vanilla Extra" }, price: null, image: "/images/vanilla_extra.jpg" },
    { name: { ar: "كراميل", en: "Caramel Extra" }, price: null, image: "/images/caramel_extra.jpg" },
    { name: { ar: "صنوبر", en: "Pine Nut Extra" }, price: null, image: "/images/pine_nut_extra.jpg" },
    { name: { ar: "شركات", en: "Companies Extra" }, price: null, image: "/images/companies_extra.jpg" },
    { name: { ar: "إكسترا خاص", en: "Special Extra" }, price: null, image: "/images/special_extra.jpg" },
    { name: { ar: "إكسترا لايت", en: "Light Extra" }, price: null, image: "/images/light_extra.jpg" },
    { name: { ar: "شاي", en: "Tea Extra" }, price: null, image: "/images/tea_extra.jpg" },
    { name: { ar: "توينج", en: "Twinge" }, price: null, image: "/images/twinge.jpg" },
    { name: { ar: "شوت إسبريسو", en: "Espresso Shot" }, price: null, image: "/images/espresso_shot.jpg" },
    { name: { ar: "خلطة فواكه", en: "Fruit Mix" }, price: null, image: "/images/fruit_mix.jpg" },
  ],
},
{
  category: { ar: "مشروبات غازية", en: "Soft Drinks" },
  items: [
    { name: { ar: "فانتا", en: "Fanta" }, price: 45, image: "/images/fanta.jpg" },
    { name: { ar: "كولا", en: "Cola" }, price: 45, image: "/images/cola.jpg" },
    { name: { ar: "زيرو كولا", en: "Zero Cola" }, price: 45, image: "/images/zero_cola.jpg" },
    { name: { ar: "فيروز", en: "Fayrouz" }, price: 45, image: "/images/fayrouz.jpg" },
    { name: { ar: "ريد بول", en: "Red Bull" }, price: 85, image: "/images/red_bull.jpg" },
    { name: { ar: "بيبسي", en: "Pepsi" }, price: 45, image: "/images/pepsi.jpg" },
    { name: { ar: "بيبسي زيرو", en: "Pepsi Zero" }, price: 45, image: "/images/pepsi_zero.jpg" },
    { name: { ar: "سبرايت", en: "Sprite" }, price: 45, image: "/images/sprite.jpg" },
    { name: { ar: "شفس", en: "Schweppes" }, price: 60, image: "/images/schweppes.jpg" },
    { name: { ar: "بيريل", en: "Birell" }, price: 65, image: "/images/birell.jpg" },
    { name: { ar: "ميريندا", en: "Mirinda" }, price: 45, image: "/images/mirinda.jpg" },
    { name: { ar: "مياه", en: "Water" }, price: 10, image: "/images/water.jpg" },
  ],
},
{
  category: { ar: "مهيتو", en: "Mojitos" },
  items: [
    { name: { ar: "مهيتو ريد بول", en: "Red Bull Mojito" }, price: 110, image: "/images/red_bull_mojito.jpg" },
    { name: { ar: "مهيتو توت", en: "Raspberry Mojito" }, price: 80, image: "/images/raspberry_mojito.jpg" },
    { name: { ar: "مهيتو بلوبيري", en: "Blueberry Mojito" }, price: 80, image: "/images/blueberry_mojito.jpg" },
    { name: { ar: "مهيتو خوخ", en: "Peach Mojito" }, price: 80, image: "/images/peach_mojito.jpg" },
    { name: { ar: "مهيتو باشن فروت", en: "Passion Mojito" }, price: 85, image: "/images/passion_mojito.jpg" },
    { name: { ar: "مهيتو فراولة", en: "Strawberry Mojito" }, price: 80, image: "/images/strawberry_mojito.jpg" },
    { name: { ar: "مهيتو كيوي", en: "Kiwi Mojito" }, price: 80, image: "/images/kiwi_mojito.jpg" },
    { name: { ar: "مهيتو كريز", en: "Cherry Mojito" }, price: 80, image: "/images/cherry_mojito.jpg" },
    { name: { ar: "مهيتو مانجو", en: "Mango Mojito" }, price: 80, image: "/images/mango_mojito.jpg" },
    { name: { ar: "مهيتو كلاسيك", en: "Classic Mojito" }, price: 80, image: "/images/classic_mojito.jpg" },
    { name: { ar: "مهيتو رمان", en: "Pomegranate Mojito" }, price: 80, image: "/images/pomegranate_mojito.jpg" },
    { name: { ar: "مهيتو ميكس", en: "Mix Mojito" }, price: 80, image: "/images/mix_mojito.jpg" },
    { name: { ar: "مهيتو سبيشال", en: "Special Mojito" }, price: 80, image: "/images/special_mojito.jpg" },
  ],
},
{
  category: { ar: "صن شاين", en: "Sunshine Drinks" },
  items: [
    { name: { ar: "صن شاين رمان", en: "Pomegranate Sunshine" }, price: 85, image: "/images/pomegranate_sunshine.jpg" },
    { name: { ar: "صن شاين بلوبيري", en: "Blueberry Sunshine" }, price: 85, image: "/images/blueberry_sunshine.jpg" },
    { name: { ar: "صن شاين نعناع", en: "Mint Sunshine" }, price: 85, image: "/images/mint_sunshine.jpg" },
    { name: { ar: "صن شاين توت", en: "Raspberry Sunshine" }, price: 85, image: "/images/raspberry_sunshine.jpg" },
    { name: { ar: "صن شاين كلاسيك", en: "Classic Sunshine" }, price: 80, image: "/images/classic_sunshine.jpg" },
    { name: { ar: "صن شاين فراولة", en: "Strawberry Sunshine" }, price: 85, image: "/images/strawberry_sunshine.jpg" },
    { name: { ar: "صن شاين مانجو", en: "Mango Sunshine" }, price: 85, image: "/images/mango_sunshine.jpg" },
    { name: { ar: "صن شاين ميكس", en: "Mix Sunshine" }, price: 90, image: "/images/mix_sunshine.jpg" },
    { name: { ar: "صن شاين بطيخ", en: "Watermelon Sunshine" }, price: 85, image: "/images/watermelon_sunshine.jpg" },
    { name: { ar: "صن شاين خوخ", en: "Peach Sunshine" }, price: 85, image: "/images/peach_sunshine.jpg" },
    { name: { ar: "صن شاين باشن فروت", en: "Passion Sunshine" }, price: 85, image: "/images/passion_sunshine.jpg" },
    { name: { ar: "صن شاين كيوي", en: "Kiwi Sunshine" }, price: 85, image: "/images/kiwi_sunshine.jpg" },
    { name: { ar: "صن شاين سبيشال", en: "Special Sunshine" }, price: 85, image: "/images/special_sunshine.jpg" },
  ],
},
{
  category: { ar: "فرابيه", en: "Frappes" },
  items: [
    { name: { ar: "فرابيه كراميل", en: "Caramel Frappe" }, price: 85, image: "/images/caramel_frappe.jpg" },
    { name: { ar: "فرابيه أوريو", en: "Oreo Frappe" }, price: 85, image: "/images/oreo_frappe.jpg" },
    { name: { ar: "فرابيه موكا", en: "Mocha Frappe" }, price: 85, image: "/images/mocha_frappe.jpg" },
    { name: { ar: "فرابيه لوتس", en: "Lotus Frappe" }, price: 90, image: "/images/lotus_frappe.jpg" },
    { name: { ar: "فرابيه شوكولاتة", en: "Chocolate Frappe" }, price: 85, image: "/images/chocolate_frappe.jpg" },
    { name: { ar: "فرابيه نوتيلا", en: "Nutella Frappe" }, price: 85, image: "/images/nutella_frappe.jpg" },
    { name: { ar: "فرابيه قهوة", en: "Coffee Frappe" }, price: 85, image: "/images/coffee_frappe.jpg" },
    { name: { ar: "فرابيه فانيلا", en: "Vanilla Frappe" }, price: 85, image: "/images/vanilla_frappe.jpg" },
    { name: { ar: "فرابيه ميكس", en: "Mix Frappe" }, price: 85, image: "/images/mix_frappe.jpg" },
    { name: { ar: "فرابيه سبيشال", en: "Special Frappe" }, price: 85, image: "/images/special_frappe.jpg" },
  ],
},
{
  category: { ar: "ايس كوفي", en: "Iced Coffee" },
  items: [
    { name: { ar: "ايس لاتيه", en: "Iced Latte" }, price: null, image: "/images/iced_latte.jpg" },
    { name: { ar: "ايس موكا", en: "Iced Mocha" }, price: null, image: "/images/iced_mocha.jpg" },
    { name: { ar: "ايس كوفي", en: "Iced Coffee" }, price: null, image: "/images/iced_coffee.jpg" },
  ],
},
{
  category: { ar: "شيشة", en: "Hookah" },
  items: [
    { name: { ar: "خلطة نكهات", en: "Mix Flavors" }, price: 140, image: "/images/hookah_mix.jpg" },
    { name: { ar: "معسل", en: "Molasses" }, price: 80, image: "/images/hookah_molasses.jpg" },
  ],
}

];
export default menu;
